### ISSUE TITLE
Postgres: Mapping columns and json_agg in the same query

### ISSUE THREAD

**Issue by cyril265** [vb-consulting/Norm.net#12]
Hey, I'm trying to map a result of json_agg combined with normal columns. 
This is the query:

```sql
    select id, foo, json_agg(
            json_build_object(
                    'Name1', t.name1,
                    'Name2', t.name2
                )
        ) from (
                      values
                          (1, 'foo1', 'testname1', 'x'),
                          (2, 'foo2', 'testname2', 'y'),
                          (2, 'foo2', 'testfoo3', 'yy'),
                          (3, 'foo3', 'testname3', 'z')
                  ) t(id, foo, name1, name2)
    GROUP BY id, foo;
```

And I'm trying to map it with the following code:

```c#
connection.ReadAsync<FirstPart, JsonPart[]>(...)

public class FirstPart
{
    public required int Id { get; init; }
    public required string Foo { get; init; }
}

public class JsonPart
{
    public required string Name1 { get; init; }
    public required string Name2 { get; init; }
}
```

The following exception is thrown:

```c#
System.InvalidCastException: Can't cast database type integer to FirstPart
   at Npgsql.Internal.TypeHandling.NpgsqlTypeHandler.ReadCustom[TAny](NpgsqlReadBuffer buf, Int32 len, Boolean async, FieldDescription fieldDescription)
   at Npgsql.NpgsqlDataReader.GetFieldValue[T](Int32 ordinal)
   at Npgsql.NpgsqlDataReader.GetFieldValueAsync[T](Int32 ordinal, CancellationToken cancellationToken)
   at Norm.Norm.GetFieldValueAsync[T](DbDataReader reader, Int32 ordinal, Type type)
   at Norm.Norm.<>c__DisplayClass108_0`2.<<ReadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Norm.Norm.ReadCallbackAsync[T](String command, Func`2 readerAction)+MoveNext()
```
It's working if I replace FirstPart with value types: `ReadAsync<int, string, JsonPart[]>`. Maybe it's the proper way of doing it and I'm just doing weird stuff 😄

**Comment by vbilopav** [comment]
Your query is returning these three fields:

 - id int
 - foo text
 - json_agg json

Therefore, if you map by name, your classes should look like this:

```csharp
public class FirstPart
{
    public required int Id { get; init; }
    public required string Foo { get; init; }
}

public class JsonPart
{
    public required string JsonAgg { get; init; }
}
```

And you can then map like this:

```csharp
            var result = connection.Read<FirstPart, JsonPart>(@"
                 select id, foo, json_agg(
                        json_build_object(
                                'Name1', t.name1,
                                'Name2', t.name2
                            )
                    ) from (
                                  values
                                      (1, 'foo1', 'testname1', 'x'),
                                      (2, 'foo2', 'testname2', 'y'),
                                      (2, 'foo2', 'testfoo3', 'yy'),
                                      (3, 'foo3', 'testname3', 'z')
                              ) t(id, foo, name1, name2)
                GROUP BY id, foo").ToList();
```

You'll get a list of tuple values where Item1 is an instance of `FirstPart` and the second part is instance of `JsonPart` classes.

Deserialization from JSON has to be done manually by Newtwonsoft JSON or System.Text.Json or similar.

Hope this helps.
