### ISSUE TITLE
PostgreSql hstore compatibility with dictionary

### ISSUE THREAD

**Issue by goncalo-oliveira** [vb-consulting/Norm.net#20]
I've got a situation with a query that returns an `hstore` type field. According to the driver [docs](https://www.npgsql.org/doc/types/basic.html), this type defaults to a `Dictionary<string, string>`.

Here's the simplified query; removed unnecessary clutter for clarity

```sql
select 
    name,
    tags::hstore
from planet_osm_roads
limit 1;
```

For this use case, I created a model class, which looks like this

```csharp
internal sealed class RoadSegmentModel
{
    public string? Name { get; set; }
    public Dictionary<string, string>? Tags { get; set; }
}
```

The type mapping I think it's accurate, because if I change it to a string, I get the following exception, which would be expected

```
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.String]' to type 'System.String'.
```

So... the code to execute the query is pretty much straightforward

```csharp
var result = await connection.ReadAsync<RoadSegmentModel>( sql )
    .ToArrayAsync();
```

However, when executing this, I'm presented with the following exception

```
System.NotImplementedException: TypeCode Object not implemented
   at Norm.Mapper.NormExtensions.CreateDelegate[T](PropertyInfo property, Boolean nullable)
   at Norm.Mapper.NormExtensions.MapInstance[T](ReadOnlyMemory`1 tuple, T& instance, MapDescriptor& descriptor, ValueTuple`7[]& delegates)
   at Norm.Mapper.NormExtensions.Map[T](IAsyncEnumerable`1 tuples, Type type1)+MoveNext()
   at Norm.Mapper.NormExtensions.Map[T](IAsyncEnumerable`1 tuples, Type type1)+MoveNext()
   at Norm.Mapper.NormExtensions.Map[T](IAsyncEnumerable`1 tuples, Type type1)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
```

Am I missing something here, maybe?

**Comment by goncalo-oliveira** [comment]
I can get around this by manually mapping the data and the object IS a `Dictionary<string, string>`.

```csharp
var manual = await connection.ReadAsync( sql ).ToArrayAsync();

var result = manual.Single();
var match = new RoadSegment();

foreach ( var item in result )
{
    switch ( item.name )
    {
        case "name":
            match.Name = (string)item.value;
            break;
        case "tags":
            match.Tags = ( (Dictionary<string, string>)item.value );
            break;
    }
}
```

**Comment by vbilopav** [comment]
Fixed it:
https://github.com/vb-consulting/Norm.net/blob/master/changelog.md#538-2023-09-07

**Comment by vbilopav** [comment]
Closing this issue
